spring.application.name=spring_security_day_29


spring.datasource.url = jdbc:mysql://localhost:3306/student_db
spring.datasource.username = root
spring.datasource.password = ${SQL_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


jwt.secret = 5de813hnxAmPpkafMYjllCzxXkEQT//F6WR4ELZwvIs=
jwt.issuer = nirajarmy-api
jwt.expiry = 900