spring.application.name=springJDBC_Demo_day20


spring.datasource.url = jdbc:mysql://localhost:3306/learn_jdbc_student_db
spring.datasource.username = root
spring.datasource.password = ${SQL_DB_PASSWORD}

